export default function Head() {
    return (
      <>
        <title>Investify</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../assets/favicon.ico" />
      </>
    )
  }