export default function Head() {
  return (
    <>
      <title>Investify</title>
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="../assets/favicon.ico" />
    </>
  );
}
